### ISSUE TITLE
Output depends on input order

### ISSUE THREAD

**Issue by coderholic** [maxmind/MaxMind-DB-Writer-perl#18]
I expected to get the same DB generated regardless of the order of my input, but that's not the case.

For example, if I create a tree with the following 2 IP ranges and input them in the order shown below then the tree contains what I'd expect:

66.17.128.0/17
66.17.185.0/24

But if I add them in the opposite order (66.17.185.0/24 first), then 66.17.185.0/24 doesn't appear in the tree at all.

Here's a simple writer script that I'm using to test this:

```perl
#!/usr/bin/perl
use MaxMind::DB::Writer::Tree;
use Net::Works::Network;

my $tree = MaxMind::DB::Writer::Tree->new(
   ip_version            => 4,
   record_size           => 24,
   database_type         => 'test',
   languages             => ['en'],
   description           => { en => 'ipinfo data' },
   map_key_type_callback => sub { 'utf8_string' },
);

foreach $line ( <STDIN> ) {
    chomp( $line );
    $tree->insert_network(
       Net::Works::Network->new_from_string( string => $line),
       {prefix => $line}
    );
}

open my $fh, '>:bytes', 'written.mmdb';
$tree->write_tree($fh);
```

I also have a simple read script, that looks up the given IP in the output database. Here's what happens with the ranges in the first order:

```bash
$ echo -e "66.17.128.0/17\n66.17.185.0/24" | ./write
$ ./read 66.17.185.5
{ prefix: '66.17.185.0/24' }
$ ./read 66.17.128.1
{ prefix: '66.17.128.0/17' }

$ strings written.mmdb | grep -o 66.*
66.17.128.0/17
66.17.185.0/24
```

And here's the second:

```bash
$ echo -e "66.17.185.0/24\n66.17.128.0/17" | ./write
$ ./read 66.17.185.5
{ prefix: '66.17.128.0/17' }
$ ./read 66.17.128.1
{ prefix: '66.17.128.0/17' }

$ strings written.mmdb | grep -o 66.*
66.17.128.0/17
```

I had expected the same database to be produced regardless of the order in which networks are added to the tree.

**Comment by autarch** [comment]
This is the expected behavior. If you add a network that contains a previously added network, the previously added network is overwritten.

There are a couple things you can do to avoid this. One option is to order your input so that smaller networks come later. This ensures that they are not overwritten.

You can also set the `merge_record_collisions` parameter to a true value when constructing a Tree object. This will cause the writer to merge two records whenever there is an overlap. This only works if your top-level record type is a map (aka hash). However, if you don't want the merge behavior, the only option is to sort the inputs.

If this isn't clear from the docs we'd definitely like to improve that. A PR to clarify this in the docs would be very welcome!

**Comment by coderholic** [comment]
OK thanks. Definitely not what I expected, but I'll re-review the documentation and see if that's an oversight on my part, or if the docs could be improved. 

Would a simple lexographical sort on the netblocks work (eg. `cat blocks | sort`), or would there be some cases where that wouldn't work?

**Comment by autarch** [comment]
I think `sort -n` should work. Looking at the docs, I don't think there's anything about insert order or how to blocks which overlap interact. I'll add that.

**Comment by autarch** [comment]
Hmm, I take that back. `sort -n` will sort 101.255 before 101.99.

You need to sort it by IP address.

**Comment by autarch** [comment]
Actually, take 3. You need to sort by network prefix length so you insert the largest networks first. Nothing else matters in terms of order.

**Comment by coderholic** [comment]
Oh of course, that's a great insight!
