### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by coderholic** [maxmind/MaxMind-DB-Writer-perl#42]
I'm having issues with encoding...

Here's my test input file:

```
$ file input
input: UTF-8 Unicode text
$ cat input
0.0.0.0/0|Cablevisión Reykjavík རེཀ་ཇ་བིཀ།Ρέικιαβικ
```

Here's my writer script:

```
use MaxMind::DB::Writer::Tree;
use Net::Works::Network;

my %types = (
    name => 'utf8_string',
);

my $tree = MaxMind::DB::Writer::Tree->new(
   ip_version            => 4,
   record_size           => 28,
   database_type         => 'encoding test',
   languages             => ['en'],
   description           => { en => 'encoding test' },
   map_key_type_callback => sub { $types{ $_[0] } },
);

foreach $line ( <STDIN> ) {
    chomp( $line );
    @parts = split(/\|/, $line);
    $tree->insert_network(
       Net::Works::Network->new_from_string( string => $parts[0]),
       {name => ($parts[1] or '')},
    );
}

open my $fh, '>:bytes', 'test.mmdb';
$tree->write_tree($fh);
```

Here's a perl reader script:

```
use MaxMind::DB::Reader;
use Data::Dumper;
my $reader = MaxMind::DB::Reader->new( file => 'test.mmdb' );
my $res = $reader->record_for_address('0.0.0.0');
print Dumper($res);
```

That outputs this:

```
$VAR1 = {
          'name' => "Cablevisi\x{c3}\x{b3}n Reykjav\x{c3}\x{ad}k \x{e0}\x{bd}\x{a2}\x{e0}\x{bd}\x{ba}\x{e0}\x{bd}\x{80}\x{e0}\x{bc}\x{8b}\x{e0}\x{bd}\x{87}\x{e0}\x{bc}\x{8b}\x{e0}\x{bd}\x{96}\x{e0}\x{bd}\x{b2}\x{e0}\x{bd}\x{80}\x{e0}\x{bc}\x{8d}\x{ce}\x{a1}\x{ce}\x{ad}\x{ce}\x{b9}\x{ce}\x{ba}\x{ce}\x{b9}\x{ce}\x{b1}\x{ce}\x{b2}\x{ce}\x{b9}\x{ce}\x{ba}",
        };
```

I also have a script that uses https://github.com/PaddeK/node-maxmind-db

```
reader = require('maxmind-db-reader')

data = reader.openSync('test.mmdb')
result = data.getGeoDataSync('0.0.0.0')
console.log result.name
```

And that outputs:

```
CablevisiÃ³n ReykjavÃ­k à½¢à½ºà½à¼à½à¼à½à½²à½à¼Î¡Î­Î¹ÎºÎ¹Î±Î²Î¹Îº
```

Any thoughts on what might be going wrong here?

**Comment by 2shortplanks** [comment]
This looks like expected behavior with the way you're using Perl.  From
what it looks like to me your terminal is set up to render utf-8 but when
you read in the data from STDIN with Perl you haven't configured Perl to
read in utf-8 so it's reading in in its default encoding, which looks like
Latin-1. Have you tried dumping @parts before you pass it to
insert_network? I'd expect it to contain the same characters.

There's more than one way to address this, most of which are covered in the
Perl Unicode cookbook here:
http://www.perl.com/pub/2012/04/perlunicook-decode-standard-filehandles-as-utf-8.html

**Comment by coderholic** [comment]
When I print parts from the write script the encoding appears correct, so
I'm not sure that is the problem.

**Comment by 2shortplanks** [comment]
I'm not sure if you mean it prints out okay from the writer script when you
Dump it with Data::Dumper or when you simply print the string.

The latter I'd expect to work even if Perl doesn't understand the encodings
correctly. This is because even though Perl doesn't know the correct
characters if it reads a sequence in in Latin-1 and writes the characters
out again as Latin-1 you're going to get the same byte sequence back out
again as you read in, which if your terminal is configured to process utf-8
will render correctly despite Perl thinking each byte in the utf-8 encoding
is a Latin-1 character. The problem would come when Perl has to understand
what characters are what when it's doing operations on each character - as
is the case when it's writing to the maxmind db format.

**Comment by coderholic** [comment]
You're absolutely right. Adding the following to the top of my write script has fixed the "problem". Thanks!

```
use open qw(:std :utf8);
```
